/**
 * Convert any string into a clean, URL-safe slug:
 * lowercase, ASCII-only, hyphen-separated.
 *
 * Mirrors the SQL `public.slugify()` function so client-side
 * fallback slugs match the ones generated by the database.
 */
export function slugify(input: string | null | undefined): string {
  if (!input) return "";
  return input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "") // strip accents
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "");
}
